# Generated by Django 5.1.2 on 2024-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
